git add SYSIBMADM.APPLICATIONS\SYSIBMADM.APPLICATIONS.sql

git add SYSIBMADM.dbpaths\SYSIBMADM.dbpaths.sql

git add SYSIBMADM.ENV_SYS_RESOURCES\SYSIBMADM.ENV_SYS_RESOURCES.sql

git add SYSIBMADM.ENV_SYS_RESOURCES\SYSIBMADM.ENV_SYS_RESOURCES_PIVOT.sql

git add sysibmadm.env_inst_info\sysibmadm.env_inst_info.sql

git add SYSIBMADM.SNAPAPPL\SYSIBMADM.SNAPAPPL.sql

git add SYSIBMADM.SNAPAPPL_INFO\SYSIBMADM.SNAPAPPL_INFO.sql

git add SYSIBMADM.SNAPTAB\SYSIBMADM.SNAPTAB.sql

git add SYSIBMADM.TBSP_UTILIZATION\SYSIBMADM.TBSP_UTILIZATION.sql

git add SYSIBMADM.TBSP_UTILIZATION\SYSIBMADM.TBSP_UTILIZATION.sql

git add SYSIBMADM.TOP_DYNAMIC_SQL\SYSIBMADM.TOP_DYNAMIC_SQL.sql

git add git*.cmd
